spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      platform: postgres

server:
  port: 9090

adapter:
  restconsumer:
    timeout: 5000
    url: "http://backend_autenticacion:8080"

cors:
  allowed-origins: "http://backend_autenticacion:4200,http://backend_autenticacion:8080"
