spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: miPassword

  sql:
    init:
      mode: always
      platform: postgres
logging:
  level:
    root=INFO:
server:
  port: 9090